#!/bin/fish

set num (ls | pcregrep -o1 "cours([0-9]+)" | sort -n |tail -n 1)
set num (math $num + 1)

printf "\\input{../parameters}\n\n\\\begin{document}\n$(date "+%Y-%m-%d")\n\n\\\end{document}" > "cours$num"".tex"

inkscape-figures watch

deep_focus

edit "cours$num"".tex"

