#!/bin/sh

start_time=$(date +%s)
end_time=$(($start_time + 3)) # 30 seconds from now

while [ "$is_done" = "" ]; do 
	echo $end_time
	if [ $(date +%s) -gt $end_time ]; then
		echo "Time limit reached, exiting loop."
		break
	fi
	sleep 1
	echo "waiting... : is_done= $is_done"
done

echo "done"
