#!/bin/bash

# shxkd stuff -----------------------------------------------------------------
fish "set -U SXHKD_SHELL sh"

# services stuff --------------------------------------------------------------
pkill -USR1 -x sxhkd &
picom --backend glx --glx-no-rebind-pixmap --glx-no-stencil --vsync&
#libinput-gestures-setup restart
xbindkeys &
copyq &
flameshot &
kstart plasmashell

pkill stupid
stupid &

# Monitor stuff ---------------------------------------------------------------
EXT_MON=$(xrandr -q | pcregrep -o1 "(\bDP[0-9]) connected")

if [[ $EXT_MON ]]; then
	bspc monitor eDP1 		-d 1 2 3 4 5
	bspc monitor $EXT_MON -d 6 7 8 9 10
else	
	bspc monitor eDP1 		-d 1 2 3 4 5 6 7 8 9 10
fi


# Basic config ----------------------------------------------------------------
bspc config bottom_padding	 		0
bspc config top_padding		 			40
bspc config border_width        0
bspc config window_gap          5

# Pywal
#. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color 	"$color1"
bspc config active_border_color 	"$color2"
bspc config focused_border_color 	"$color15"
bspc config presel_feedback_color "$color1"

bspc config pointer_mod         mod1
bspc config pointer_action1     move
bspc config pointer_action2			resize_corner
bspc config pointer_action2			resize_side

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Window rules ----------------------------------------------------------------

# Make every window folating by default
bspc rule -a \* state=floating center=true

# Tiled windows!
bspc rule -a Alacritty state=tiled center=true rectangle=1001x760+0+0
bspc rule -a Blender state=tiled
bspc rule -a Code state=tiled
bspc rule -a dolphin state=tiled
bspc rule -a firefox state=tiled
bspc rule -a Google-chrome state=tiled
bspc rule -a imv state=tiled
bspc rule -a Inkscape state=fullscreen
bspc rule -a "kdeconnect.daemon" state=fullscreen
bspc rule -a kitty state=tiled center=true rectangle=1418x860+0+0
bspc rule -a Mathematica state=pseudo_tiled
bspc rule -a nvim-qt state=tiled bspc rule -a obsidian state=tiled
bspc rule -a Steam state=tiled center=true rectangle=1001x760+0+0
bspc rule -a Surf state=tiled center=true rectangle=1001x760+0+0
bspc rule -a URxvt state=tiled center=true rectangle=1418x860+0+0
bspc rule -a \teams state=tiled
bspc rule -a Xournalpp state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Zotero state=tiled


# bspc scipts! ----------------------------------------------------------------
$HOME/scripts/bspi_listen.sh &
pgrep bspswallow || bspswallow &
killall bspc_color_border; $HOME/scripts/bspc_color_border &

# Other -----------------------------------------------------------------------
sed -i s/".*background.*"//g .cache/wal/colors.Xresources
sed -i s/".*border.*"//g .cache/wal/colors.Xresources
xrdb /home/amda/.config/.Xresources
xrdb -merge .cache/wal/colors.Xresources
sxhkd &

setxkbmap -option caps:swapescape


makefloat && urxvt -e fish -c "cbonsai -m (bad)"
