#!/bin/bash

# shxkd stuff -----------------------------------------------------------------
fish "set -U SXHKD_SHELL sh"

# services stuff --------------------------------------------------------------
pkill -USR1 -x sxhkd &
picom --backend glx --glx-no-rebind-pixmap --glx-no-stencil --vsync&

if [[ "$1" = 0 ]]; then
	#libinput-gestures-setup restart
	xbindkeys &
	copyq &
	flameshot &
	kstart plasmashell

	#pkill stupid
	stupid &

	gpt_wisdom() {
		# wait for internet connection else "bad" will fail
		while [[ "$(nmcli -t -f STATE g)" != "connected" ]]; do
			sleep 1
		done
		# gives a great live advice
		makefloat && $TERMINAL -e fish -c "cbonsai -m (bad)"
	}
	
	gpt_wisdom &
fi

# Monitor stuff ---------------------------------------------------------------
EXT_MON=$(xrandr -q | pcregrep -o1 "(\bDP.+) connected")

if [[ $EXT_MON ]]; then
	if [[ $(xrandr | grep $EXT_MON | grep primary -o) ]]; then
		bspc monitor $EXT_MON -d I    II   III  IV   V
		bspc monitor eDP1 		-d VI   VII  VIII IX   X
	else
		bspc monitor eDP1 		-d I    II   III  IV   V
		bspc monitor $EXT_MON -d VI   VII  VIII IX   X
	fi
else	
	bspc monitor eDP1 			-d I    II   III  IV   V   VI   VII  VIII IX X
fi


# Basic config ----------------------------------------------------------------
bspc config bottom_padding	 		0
bspc config top_padding		 			40
bspc config border_width        0
bspc config window_gap          5

# Pywal
#. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color 	"#6C7087"
bspc config active_border_color 	"$color2"
bspc config focused_border_color 	"#AAAAED"
bspc config presel_feedback_color "$color1"

bspc config pointer_mod         mod1
bspc config pointer_action1     move
bspc config pointer_action2			resize_corner
bspc config pointer_action2			resize_side

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Window rules ----------------------------------------------------------------

# Make every window folating by default
bspc rule -a \* state=floating center=true

# Tiled windows!
bspc rule -a Alacritty state=tiled center=true rectangle=1001x760+0+0
bspc rule -a Blender state=tiled
bspc rule -a Code state=tiled
bspc rule -a dolphin state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a firefox state=tiled
bspc rule -a Google-chrome state=tiled
bspc rule -a imv state=tiled
bspc rule -a Inkscape state=fullscreen
bspc rule -a "kdeconnect.daemon" state=fullscreen
bspc rule -a kitty state=tiled center=true rectangle=1418x860+0+0
bspc rule -a libreoffice-impress state=tiled
bspc rule -a Mathematica state=pseudo_tiled
bspc rule -a nvim-qt state=tiled bspc rule -a obsidian state=tiled
bspc rule -a Slack state=floating center=true
bspc rule -a "Soffice" state=tiled
bspc rule -a Steam state=tiled center=true rectangle=1001x760+0+0
bspc rule -a Surf state=tiled center=true rectangle=1001x760+0+0
bspc rule -a \teams state=tiled
bspc rule -a URxvt state=tiled center=true rectangle=1418x860+0+0
bspc rule -a "VirtualBox Machine" state=tiled center=true rectangle=1418x860+0+0
bspc rule -a Xournalpp state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Zotero state=tiled



# Other -----------------------------------------------------------------------
sed -i s/".*background.*"//g .cache/wal/colors.Xresources
sed -i s/".*border.*"//g .cache/wal/colors.Xresources
xrdb /home/amda/.config/.Xresources
#xrdb -merge .cache/wal/colors.Xresources
sxhkd &

setxkbmap -option caps:escape
#setxkbmap -option caps:swapescape

if [[ "$1" = 0 ]]; then	
	sleep 20
	# bspc scipts! ----------------------------------------------------------------
	killall bspc_color_border
	$HOME/scripts/bspwm/bspc_color_border &
	#$HOME/scripts/bspwm/bspi_listen.sh &
	pgrep bspswallow || bspswallow &
fi
