#!/bin/bash

fis "set -U SXHKD_SHELL sh"

xrdb /home/amda/.Xressources

sxhkd &

libinput-gestures-setup restart
systemctl start bluetooth.service
killall polybar
#$HOME/.config/polybar/launch.sh &
picom --experimental-backends --backend glx &
copyq &
pkill Discord
discord --start-minimized &
killall slack
slack -u &
flameshot &
appim/Mathpix_Snipping_Tool-x86_64.v03.00.0050.AppImage &
# bspc rule -a \* -o state=floating rectangle=1800x1000+0+0 && kdocker -l -q -i/usr/share/icons/hicolor/24x24/apps/spotify-client.png spotify &

EXT_MON=$(xrandr -q | pcregrep -o1 "(\bDP[0-9]) connected")

if [[ $EXT_MON ]]; then
#	xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --above eDP
	bspc monitor eDP1 -d 1 2 3 4 5
	bspc monitor $EXT_MON -d 6 7 8 9 10
else	
	bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
fi

xrdb -merge .cache/wal/colors.Xresources

bspc config bottom_padding	 0
bspc config top_padding		 40
bspc config border_width         0
bspc config window_gap           5

setxkbmap -option caps:swapescape
$$\dotsb$$ 

#Pywal--------------------------------------

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
bspc config presel_border_color "$color1"

bspc config pointer_mod         mod1
bspc config pointer_action1     move
bspc config pointer_action2		resize_corner
bspc config pointer_action2		resize_side

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
# Make every window folating by default
bspc rule -a \* state=floating

# Tiled windows!
bspc rule -a \teams state=tiled
bspc rule -a Code state=tiled
bspc rule -a obsidian state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Alacritty state=tiled center=true rectangle=804x600+0+0
bspc rule -a URxvt state=tiled center=true rectangle=804x600+0+0
bspc rule -a Google-chrome state=tiled
bspc rule -a Surf state=tiled
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a copyq state=floating
bspc rule -a discord state=floating center=true rectangle=1800x1000+0+0
bspc rule -a dolphin state=floating center=true rectangle=1000x600+0+0

bspc rule -a Slack state=floating center=true rectangle=1800x1000+0+0
bspc rule -a "Mathpix Snipping Tool" state=floating center=true
#bspc rule -a Nautilus state=floating
#bspc rule -a Org.gnome.Nautilus state=floating
#bspc rule -a File-roller state=floating
bspc rule -a mpv state=floating border=off
#bspc rule -a matplotlib state=floating
#bspc rule -a Matplotlib state=floating
#bspc rule -a Peek state=floating
bspc rule -a spotify state=floating center=true rectangle=1800x1000+0+0
#bspc rule -a "*:*:Live Caption" state=floating
#bspc rule -a '*:blueman-manager' state=floating

#TouchPad stuff
# id=$(xinput | grep SynPS/2 | pcregrep -o1 "id=([0-9]+)")
# prop=$(xinput list-props $id | grep "Synaptics Scrolling Distance" | pcregrep -o1 "\(([0-9]+)\)")
# xinput set-prop $id $prop -112 -112
# synclient AreaLeftEdge=1700
# synclient AreaRightEdge=4335
# synclient HorizTwoFingerScroll=1

#bash $HOME/.config/bspwm/bspwm_colors.sh &
bash $HOME/scripts/bspi_listen.sh &

#pkill -USR1 -x sxhkd
wal -R  

# bspc rule -a \* -o state=floating && urxvt -e pipes.sh

pgrep bspswallow || bspswallow &
