#!/bin/bash

DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

SERVICE=$1
NODE_ID=$(cat $DIR/$SERVICE.dat)

if pgrep -x "$SERVICE" --ignore-case >/dev/null 
then
    echo "$SERVICE is running"
    hidden=$(bspc query -N -n .hidden -n $NODE_ID)
    if [ -z "$hidden" ]; then
        here=$(bspc query -N -n $NODE_ID.local)
        if [ -z "$here" ]; then
            echo "node is not hidden but not on current desktop, shifting here..."
            bspc node $NODE_ID -d $(bspc query -D -d focused)
        else
            echo "hidding node"
            bspc node $NODE_ID -g hidden=on
        fi
    else
        echo "unhidding node"
        bspc node $NODE_ID -g hidden=off
        bspc node $NODE_ID -d $(bspc query -D -d focused)
    fi
else
    echo "$SERVICE is stopped"
    echo "starting $SERVICE..."
		$SERVICE &> /dev/null &
    sleep 2
    NODE_ID=$(bspc query -N -n newest)
    echo "starting in window $NODE_ID"
    echo $NODE_ID > $DIR/$SERVICE.dat
fi
