#!/bin/bash

wid=$1;

# get window dimentions
read -r w h <<<$(wattr wh $wid);

# get screen dimentions
#res=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
#test=$(xrandr | grep -w $(bspc query -M -m focused --names))
#echo $test
#res=$(xrandr | grep -w $(bspc query -M -m focused --names) | awk '{print $4}' | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
res=$(xrandr | grep -w $(bspc query -M -m focused --names) | awk '{match($0, /[0-9]+x[0-9]+/); print substr($0, RSTART, RLENGTH)}')
echo $res

read -r X Y <<<${res/x/ }

newx=$(expr $X / 2 - $((w / 2)))
newy=$(expr $Y / 2 - $((h / 2)))

wtp $newx $newy $w $h $wid
