#!/bin/bash

wid=$1;

# get window dimentions
read -r w h <<<$(wattr wh $wid);

# get screen dimentions
res=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
read -r X Y <<<${res/x/ }

# move away in two step (better for animation)
newx=$(expr $X / 2 - $((w / 2)))
newy=$(expr $((- h )))
wtp $newx $newy $w $h $wid

sleep 0.1
newy=$(expr $((- 2 * h )))
wtp $newx $newy $w $h $wid
