height: 40
position: top
layer: bottom
start:
  - type: workspaces
    markup: true
center:
  - type: clock
    markup: true
    format: |-
      <span size="large" weight="bold">%H:%M:%S</span>
      <span>%A, %B %d, %Y</span>
    justify: center
end:
  - type: sys_info
    format: 
    - " {cpu_percent}%"
    - " {memory_percent}%"
    - " {temp_c:coretemp-Package-id-0}°C"
    - " {disk_free:/}GB"
  - type: tray
  # - type: bluetooth
  - type: network_manager
    icon_size: 20
  - type: bindmode
  - type: volume
